QuintaApp/QuintaApp/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuintaApp.Models
{
    public class Funcionario
    {
        public ushort FuncId { get; set; }
        public string FuncNome { get; set; }
        public string FuncFuncao { get; set; }
    }
}

QuintaApp/QuintaApp/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace QuintaApp.Models
{
    public class Usuario
    {
        public int UsuId { get; set; }
        [Required (ErrorMessage = "O nome é obrigatório")] //Professor, tentei de todas as maneiras colocar validação, porám nenhuma delas deu certo, e eu n vi motivo para nenhuma delas falharem, por isso, deixarei assim mesmo
        public string UsuNome { get; set; }
        [Required(ErrorMessage = "O nome é obrigatório")]
        public string UsuObs { get; set; }
        public DateTime UsuNasc { get; set; }
        public string UsuEmail { get; set; }
        public string UsuLogin { get; set; }
        public string UsuSenha { get; set; }
        public string UsuConfirmarSenha { get; set; }

    }
}

QuintaApp/QuintaApp/Controllers/FuncionarioController.cs
using QuintaApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuintaApp.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult Index()
        {
            Funcionario func = new Funcionario()
            {
                FuncId = 1,
                FuncNome = "Bronquinho",
                FuncFuncao = "Fulião"
                
            };
            return View(func);
        }

        [HttpPost]
        public ActionResult Listar(Funcionario funcionario)
        {
            return View(funcionario);
        }

    }
}

QuintaApp/QuintaApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuintaApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

QuintaApp/QuintaApp/Controllers/UsuarioController.cs
using QuintaApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace QuintaApp.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            var usuario = new Usuario();
            return View(usuario);
        }

        [HttpPost]
        public ActionResult Index(Usuario usuario)
        {

            if (ModelState.IsValid)
            {
                return View("Resultado", usuario);
            }
            return View(usuario);
        }

        public ActionResult Resultado (Usuario usuario)
        {
            return View(usuario);
        }
    }
}

QuintaApp/QuintaApp/Views/Funcionario/Index.cshtml
@model  QuintaApp.Models.Funcionario
@{
    ViewBag.Title = "Index";
}

<h2>Funcionário</h2>

@*<form action="~/Funcionario/Listar" method="post">*@

    @using (Html.BeginForm("Listar", "Funcionario", FormMethod.Post))
    {

    <fieldset>
        <legend> Dados de Funcionário</legend>
    </fieldset>

    <div>
        <label for="fundId">Código</label>
    </div>

    <div>
        <input type="number" value="@Model.FuncId" name="FuncId" />
    </div>
    <br />

    <div>
        <label for="fundNome">Nome</label>
    </div>

    <div>
        <input type="text" value="@Model.FuncNome" name="FuncNome" />
    </div>
    <br />

    <div>
        <label for="fundFuncao">Função</label>
    </div>

    <div>
        <input type="text" value="@Model.FuncFuncao" name="FuncFuncao" />
    </div>
    <br/>

    <input type="submit" value="Enviar" />
    }


@*</form>*@

QuintaApp/QuintaApp/Views/Funcionario/Listar.cshtml
@model QuintaApp.Models.Funcionario
@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<div>
    <b>Id Funcionário</b>
</div>

<div>
    @Model.FuncId
</div>

<div>
    <b>Nome do Funcionário</b>
</div>

<div>
    @Model.FuncNome
</div>

<div>
    <b>Função do Funcionário</b>
</div>

<div>
    @Model.FuncFuncao
</div>
<br/>

@Html.ActionLink("Voltar","Index","Home")

QuintaApp/QuintaApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

QuintaApp/QuintaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Funcionário", "Index", "Funcionario")</li>
                    <li>@Html.ActionLink("Usuário", "Index", "Usuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

QuintaApp/QuintaApp/Views/Usuario/Index.cshtml
@model QuintaApp.Models.Usuario
@{
    ViewBag.Title = "Index";
}

<h2>Validação de Usuário</h2>

@using (Html.BeginForm("Resultado", "Usuario", FormMethod.Post))
{
    @Html.ValidationSummary(true)

<fieldset>
    <legend> Dados do Usuário</legend>

    @*<div class="editor-label">
            @Html.LabelFor(m => m.UsuNome)
        </div>*@

    <div>
        <b>Nome do Usuário</b>
    </div>

    @**@<div class="editor-field">
        @Html.EditorFor(m => m.UsuNome)
        @Html.ValidationMessageFor(m => m.UsuNome)
    </div>

    <div>
        <b>Observações</b>
    </div>

    @*<div class="editor-label">
        @Html.LabelFor(m => m.UsuObs)
    </div>*@

    <div class="editor-field">
        @Html.TextAreaFor(m => m.UsuObs)
        @Html.ValidationMessageFor(m => m.UsuObs)
    </div>

    <div>
        <b>Data de Nascimento</b>
    </div>

    @*<div class="editor-label">
        @Html.LabelFor(m => m.UsuNasc)
    </div>*@

    <div class="editor-field">
        @Html.EditorFor(m => m.UsuNasc)
        @Html.ValidationMessageFor(m => m.UsuNasc)
    </div>

    <div>
        <b>Email</b>
    </div>

    @*<div class="editor-label">
        @Html.LabelFor(m => m.UsuEmail)
    </div>*@

    <div class="editor-field">
        @Html.EditorFor(m => m.UsuEmail)
        @Html.ValidationMessageFor(m => m.UsuEmail)
    </div>

    <div>
        <b>Login</b>
    </div>

    @*<div class="editor-label">
        @Html.LabelFor(m => m.UsuLogin)
    </div>*@

    <div class="editor-field">
        @Html.EditorFor(m => m.UsuLogin)
        @Html.ValidationMessageFor(m => m.UsuLogin)

        <div>
            <b>Senha</b>
        </div>

        @*<div class="editor-label">
            @Html.LabelFor(m => m.UsuSenha)
        </div>*@

        <div class="editor-field">
            @Html.PasswordFor(m => m.UsuSenha)
            @Html.ValidationMessageFor(m => m.UsuSenha)

            <div>
                <b>Confirmar Senha</b>
            </div>
        </div>

       @* <div class="editor-label">
            @Html.LabelFor(m => m.UsuConfirmarSenha)
        </div>*@

        <div class="editor-field">
            @Html.PasswordFor(m => m.UsuConfirmarSenha)
            @Html.ValidationMessageFor(m => m.UsuConfirmarSenha)
        </div>
    </div>
    <br />

    <p> <input type="submit" value="Cadastrar" /> </p>

</fieldset>
    
}

QuintaApp/QuintaApp/Views/Usuario/Resultado.cshtml
@model QuintaApp.Models.Usuario
@{
    ViewBag.Title = "Resultado";
}

<h2>Listar Usuário</h2>

<fieldset>
    <legend>Usuário Cadastrado</legend>

    <div>
        <b>Nome do Usuário</b>
    </div>

    @* <div class="editor-label">
            @Html.DisplayNameFor(m => m.UsuNome)
        </div>*@

    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuNome)
    </div>

    <div>
        <b>Observações</b>
    </div>

    @*<div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuObs)
    </div>*@

    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuObs)
    </div>

    <div>
        <b>Data de Nascimento</b>
    </div>

    @*<div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuNasc)
    </div>*@

    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuNasc)
    </div>

    <div>
        <b>Email</b>
    </div>

    @*<div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuEmail)
    </div>*@

    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuEmail)
    </div>

    <div>
        <b>Login</b>
    </div>

    @*<div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuLogin)
    </div>*@

    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuLogin)
    </div>

    <div>
        <b>Senha</b>
    </div>

    @*<div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuSenha)
    </div>*@

    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuSenha)
    </div>

    <div>
        <b>Confirmar Senha</b>
    </div>

    @*<div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuConfirmarSenha)
    </div>*@

    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuConfirmarSenha)
    </div>
</fieldset>


@Html.ActionLink("Voltar", "Index")